apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashi-app
  namespace: vault-hashitalks
  labels:
    app: hashi-app
spec:
  selector:
    matchLabels:
      app: hashi-app
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-status: 'update'
        vault.hashicorp.com/agent-inject-secret-database-config: 'database/rds/postgres/vault-hashi-talks-mock/creds/readonly'
        vault.hashicorp.com/agent-inject-template-database-config: |
          {{ with secret "database/rds/postgres/vault-hashi-talks-mock/creds/readonly" -}}
            export DATABASE_USER="{{ .Data.username }}"
          {{- end }}
          {{ with secret "database/rds/postgres/vault-hashi-talks-mock/creds/readonly" -}}
            export DATABASE_PASSWORD="{{ .Data.password }}"
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-database-conn: 'internal/data/database/config'
        vault.hashicorp.com/agent-inject-template-database-conn: |
          {{ with secret "internal/data/database/config" -}}
            export DATABASE_HOST="{{ .Data.data.database_host }}"
          {{- end }}
          {{ with secret "internal/data/database/config" -}}
            export DATABASE_NAME="{{ .Data.data.database_name }}"
          {{- end }}
        vault.hashicorp.com/role: 'vault-hashitalks-role'
      labels:
        app: hashi-app
    spec:
      serviceAccountName: vault-hashitalks
      containers:
        - name: hashiapp
          image: docker.io/igoritosousa22/postgrees-live:2022-07-22
          command: ['/bin/bash']
          args: ['-c', '. /vault/secrets/database-config && . /vault/secrets/database-conn && /app/postgrees-live']